#!/bin/bash


if [ "${#}" -eq 0 ] || [ "${#}" -gt 2 ]; then
	exit 1
fi

USERNAME=${SUDO_USER:-$(id -u -n)}
HOMEDIR="/home/$USERNAME"

SIGEXT=9
SIGFLE=110
SIGTRM=111
SIGWEB=112
SIGTXT=113
SIGVIS=114
SIGMUS=115
APP=""

if [ "$DESKTOP_SESSION" == dwm ]; then
	{ /usr/bin/bash "$HOMEDIR"/.script/dwm-sendsignal "${1}" ;  }
else
	if [ "${1}" -eq "$SIGFLE" ]; then
		if [ -n "${FILEMANAGER}" ]; then
			APP="$FILEMANAGER"
		else
			{ exec exo-open --launch "FileManager" & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGWEB" ]; then
		if [ -n "${BROWSER}" ]; then
			APP="$BROWSER"
		else
			{ exec exo-open --launch "WebBrowser" & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGMUS" ]; then
		if [ -n "${MUSPLAYER}" ]; then
			APP="$MUSPLAYER"
		else
			if [ -n "${TERMINAL}" ]; then
				{ exec "$TERMINAL" -e cmus & } &> /dev/null
			else
				{ exec st -e cmus & } &> /dev/null
			fi
		fi
	elif [ "${1}" -eq "$SIGTRM" ]; then
		if [ -n "${TERMINAL}" ]; then
			APP="$TERMINAL"
		else
			{ exec  exo-open --launch "TerminalEmulator" & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGTXT" ]; then
		if [ -n "${EDITOR}" ]; then
			if [ -n "${TERMINAL}" ]; then
				{ exec "$TERMINAL" -e "$EDITOR" & } &> /dev/null
			else
				{ exec st -e "$EDITOR" & } &> /dev/null
			fi
		else
			{ exec st -e vim & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGVIS" ]; then
		if [ -n "${VISEDIT}" ]; then
			APP="$VISEDIT"
		elif [ -n "${VISUAL}" ]; then
			if [ -n "${TERMINAL}" ]; then
				{ exec "$TERMINAL" -e "$VISUAL" & } &> /dev/null
			else
				{ exec st -e "$VISUAL" & } &> /dev/null
			fi
		else
			{ exec st -e vim & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGEXT" ]; then
		{ /usr/bin/bash "$HOMEDIR"/bin/logoff ;  }
	fi
fi

if [ -n "$APP" ] ;then
	if [ "$2" = "-r" ] ;then
		. "$HOMEDIR/bin/raise_or_run" "$APP"
	else
		{ exec "$APP" & } &> /dev/null
	fi
fi

