#!/bin/bash


if [ "${#}" -ne 1 ]; then
	exit 1
fi

USERNAME=${SUDO_USER:-$(id -u -n)}
HOMEDIR="/home/$USERNAME"

SIGEXT=9
SIGFLE=110
SIGTRM=111
SIGWEB=112

if [ "$DESKTOP_SESSION" == dwm ]; then
	{ /usr/bin/bash "$HOMEDIR"/.script/dwm-sendsignal "${1}" ;  }
else
	if [ "${1}" -eq "$SIGFLE" ]; then
		if [ -n "${FILEMANAGER}" ]; then
			{ exec "$FILEMANAGER" & } &> /dev/null
		else
			{ exec /usr/bin/pcmanfm & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGWEB" ]; then
		if [ -n "${BROWSER}" ]; then
			{ exec "$BROWSER" & } &> /dev/null
		else
			{ exec /usr/bin/firefox & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGTRM" ]; then
		if [ -n "${TERMINAL}" ]; then
			{ exec "$TERMINAL" & } &> /dev/null
		else
			{ exec /usr/bin/urxvt & } &> /dev/null
		fi
	elif [ "${1}" -eq "$SIGEXT" ]; then
		{ /usr/bin/bash "$HOMEDIR"/bin/logoff ;  }
	fi
fi

