#!/bin/sh
#raise or run the program

WINS="$(wmctrl -lp)"

pgrep -x "$1" | while read -r line ; do
        win="$(echo "$WINS" | \
        awk '{if ($2 >= 0 && $3 == i) print $1}' \
        i="${line}")"

        if [ -n "$win" ];then
                wmctrl -a "$win" -i
                exit 100
        fi
done

if [ $? -ne 100 ]; then
        exec "${1}" &
fi

