#!/bin/sh
#raise or run the program

WINS="$(wmctrl -lp)"
pgrep -x "$1" | while read -r line ; do
        win="$(echo "$WINS"\
     | grep "^0x[0-9a-f]\+[[:space:]]\+[0-9]\+[[:space:]]${line}"\
     | awk '{print $1}')"
        if [ -n "$win" ];then
                wmctrl -a "$win" -i
                exit 100
        fi
done

if [ $? -ne 100 ]; then
        exec "${1}" &
fi

